import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Sidebar from "@/components/layout/Sidebar";
import { AuthProvider } from "@/lib/AuthContext";
import AuthGuard from "@/lib/AuthGuard";
import ContentWrapper from "@/components/layout/ContentWrapper";

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-slate-950 text-slate-50">
        <AuthProvider>
          <AuthGuard>
            <ContentWrapper>{children}</ContentWrapper>
          </AuthGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
